### PR TITLE
Tweak README.md links

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by Acconut** [comment]
Thanks, I like your little changes, but is there a reason why "configuration object" does not link go Godoc anymore?

**Comment by gingermusketeer** [comment]
I didn't realise the links were meant to point to the go docs... I will update the PR

**Comment by Acconut** [comment]
Oh, my fault. I didn't realize they never linked to Godoc. Please change this :)

**Comment by Acconut** [comment]
Thanks a lot :)

**Comment by gingermusketeer** [comment]
No problem :)

**Pull request merged**
