### PR TITLE
Implement Azure store

### PR DESCRIPTION
**Pull request by omBratteng**
Related issue #401

This store uses only Block Blobs. Therefore supports files up to 190.7TiB.
Uses the latest version of https://github.com/Azure/azure-storage-blob-go and supports [Microsoft Service Version `2019-12-12`](https://docs.microsoft.com/en-us/rest/api/storageservices/version-2019-12-12)

Includes automated test for the store, but not the service. As I have not been able to use gock to mock the HTTP responses, I think this is because `azure-storage-blob-go` has used their own http.Client through `azure-pipeline-go`.
But uploads have been tested with [uppy](https://uppy.io/), [tusc](https://github.com/jackhftang/tusc) and [tuspy](https://github.com/vayam/tuspy). With chunk sizes above 4MiB

Additional features allows you to specify the access type of the container upon creating (if it does not already exist, limited by the storage account support).
https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure

And the blob access tier; inferred (inherited from container default), hot, cool and archive.
https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#access-tiers-for-block-blob-data

### CODE REVIEW

**Comment by omBratteng** [comment]
I just realised the tests uses Go v1.12.x and v1.13.x. Which causes some trouble.
By downgrading `azure-storage-blob-go` to `v0.11.0`, it would pass in go v1.13.x
But

**Comment by omBratteng** [comment]
@Acconut I did a test in our repo, by changing the test targets to match your https://github.com/tus/tusd/blob/master/docs/installation.md, i.e. v1.14 and v1.15, tests are passing fine.
https://github.com/arkivverket/tusd/actions/runs/530638133

The branch I tested on is based on this branch, only change I did was the testing matrix, and I removed the build stage, as it would never run in my test branch.
https://github.com/arkivverket/tusd/commit/fa264a35565f2366cd5052384081b1f1cb118250

Please let me know if you have any questions, or need some changes done.
As stated earlier, we have assigned resources to be able to resolve this implementation.

**Comment by Acconut** [comment]
First of all, thank you for this amazing PR and apologies for my late reply! 

> But uploads have been tested with [uppy](https://uppy.io/), [tusc](https://github.com/jackhftang/tusc) and [tuspy](https://github.com/vayam/tuspy). With chunk sizes above 4MiB

Have you also tested this without specifying any chunk size at all? For example, in Uppy the `chunkSize` option is not mandatory and rarely necessary.

> Which means 1.14 and 1.15 should be the test targets?

Yes, feel free to adjust the Go versions in your branch!

> Please let me know if you have any questions, or need some changes done.

I wanted to have a look at this today but noticed that @Benehiko also updated their PR https://github.com/tus/tusd/pull/407 in the meantime. Maybe you can head over there quickly and see which PR is better and on which we should move our focus :)

**Comment by omBratteng** [comment]
> > But uploads have been tested with [uppy](https://uppy.io/), [tusc](https://github.com/jackhftang/tusc) and [tuspy](https://github.com/vayam/tuspy). With chunk sizes above 4MiB
> 
> Have you also tested this without specifying any chunk size at all? For example, in Uppy the `chunkSize` option is not mandatory and rarely necessary.

Yes, I have tried without specifying any chunksize, it it too, works nicely.

> > Which means 1.14 and 1.15 should be the test targets?
> 
> Yes, feel free to adjust the Go versions in your branch!

I have adjusted the go versions in the workflow to be 1.15 and 1.16, as they're the latest versions now.
And I changed the test strategy to not fail fast, so it allows all tests to run, even if other fails. That way, in my opinion, it is easier to trace any testing issues related specifically to an OS version or go version being tested. But that commit can be reverted, let me know what you think.

> > Please let me know if you have any questions, or need some changes done.
> 
> I wanted to have a look at this today but noticed that @Benehiko also updated their PR #407 in the meantime. Maybe you can head over there quickly and see which PR is better and on which we should move our focus :)

I might be biased and prefer my PR.
But I have implemented the possibility to change the blob tier. E.g. you only upload for long term archiving, you don't need it to be in the hot tier, but perhaps cool or archive tier.
Same goes with the container (bucket) access type.

**Comment by omBratteng** [comment]
@Acconut In the future, it might be nice to look at adding concurrent support for this implementation. BlockBlobs lets you upload blocks in any order you want, and when you're done, commit the order of the blocks (block list).

**Review by Benehiko — COMMENTED** [review]
I have reviewed this and it looks really similar to my last commit before my major refactor which can be found here https://github.com/Benehiko/tusd/commit/df249230ad0d79b1952b8b52658a82006cc7730c

I'm also not really sure what is implemented better here than from mine. Sure there are 2 flags to customise when creating a container and a blob. I also see here it only implements block blobs, which is fine i guess. According to the microsoft docs "An append blob is comprised of blocks and is optimized for append operations." - so i guess the tusd server might benefit from this when tons of "smaller" files are uploaded, which can be the size of 195GiB.

**Comment by erlendvollset** [comment]
Really nice work here! Any updates on getting this or #407 merged? I have a use case requiring gcp, s3, _and_ azure blob backends, so I would really like to use this feature.

**Comment by omBratteng** [comment]
@Acconut I see there's an upcoming v2 release, I've tested my PR against the latest v2 branch, and so far, it is working fine. Although the tests are failing on s3store, but I see they're doing the same here (https://github.com/tus/tusd/actions/runs/885415253)

**Comment by Acconut** [comment]
Thank you very much for the hard work and the patience with us! Since the other PR has been closed by its maintainer, I am going to merge this beast and so how it holds up! :tada:

**Review by Acconut — APPROVED** [review]

**Pull request merged**
