### PR TITLE
Azure store implementation

### PR DESCRIPTION
**Pull request by Benehiko**
Azure store implementation involves the usage of Append Blobs and Block Blobs.
Append Blobs are used for files under 195GB 
Block Blobs are used for files above 195GB
Info file is by default an Append Blob.

Issue #401

Please note, this implementation still needs automated tests. As far as I have tested manually (with go-tus and tus-js-client) file can be paused, restarted, "crash" from server side and "crash" from client side still continued the file upload.

### CODE REVIEW

**Comment by Acconut** [comment]
Thank you very much for this massive PR! Can you explain how it works for people who have never used Azure before? Like, what are append blobs, block blobs and pipelines?

> Please note, this implementation still needs automated tests. As far as I have tested manually (with go-tus and tus-js-client) file can be paused, restarted, "crash" from server side and "crash" from client side still continued the file upload.

It's good to hear that the implementation is working. That being said, we would need automated tests for merge this PR, just to be safe that we don't accidentally introduce regressions in the future.

**Comment by Benehiko** [comment]
Hi @Acconut it's no trouble. 
I don't currently have much time to implement the automated tests - but I will do so when I have a chance.

This implementation could probably provide a bit more customization for the user (such as a user choosing which type of Blob they'd want to use via a config) - but for now I thought the best would be to automatically decide on size. Append Blobs support about 195GB max size (50,000 blocks * 4MiB per block) while Block Blobs support about 4.75TB max size (50,000 blocks * 100MiB). _Please note that the [API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs) have different max values than the [azure-blob-storage-go library](https://github.com/Azure/azure-storage-blob-go) since the last library version was 2018-11-09 while the REST API version is on 2019-12-12_.

Block Blobs also provide you with access to each individual block on the blob which can be deleted / updated etc. Append Blobs do not, since it just appends to the last block.

According to [Microsoft docs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs):

> The storage service offers three types of blobs, block blobs, append blobs, and page blobs. You specify the blob type when you create the blob. Once the blob has been created, its type cannot be changed, and it can be updated only by using operations appropriate for that blob type, i.e., writing a block or list of blocks to a block blob, appending blocks to a append blob, and writing pages to a page blob.

This implementation uses only Append and Block Blobs (which are the more common types in Azure storage).
Append Blobs according to [Microsoft docs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs):

> An append blob is comprised of blocks and is optimized for append operations. When you modify an append blob, blocks are added to the end of the blob only, via the Append Block operation. ..... Each block in an append blob can be a different size, up to a maximum of 4 MiB, and an append blob can include up to 50,000 blocks. 

Blob Blobs according to [Microsoft docs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs):

> Block blobs are optimized for uploading large amounts of data efficiently. Block blobs are comprised of blocks, each of which is identified by a block ID. A block blob can include up to 50,000 blocks. Each block in a block blob can be a different size, up to the maximum size permitted for the service version in use.

A Pipeline is a customization which you add to your requests, in this case it adds the user storage account credentials but can also add extra options such as RetryPolicies with the PipelineOptions object. Here is an explanation to it in the [azure-storage-blob-go library](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#NewPipeline).

azure-storage-blob-go library

- [AppendBlobs](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#AppendBlobURL)
- [BlockBlobs](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#BlockBlobURL)

**Comment by Acconut** [comment]
Thanks for the explanation, @Benehiko! I just wanted to ask if there is any update on the automated tests? :)

**Comment by perbu** [comment]
fwiw it is worth I've been testing manually this for a few days and everything seems to work as expected. I had to reduce chunk size to 4MiB but after that it was all good.

**Comment by Acconut** [comment]
Thanks for the feedback, @perbu! It's great to hear good results but having to reduce the chunk size in order to get it working rings some alarm bells in my mind.

**Comment by omBratteng** [comment]
@Benehiko the latest version of https://github.com/Azure/azure-storage-blob-go supports service version 2019-12-12

**Comment by Acconut** [comment]
Good to know, @omBratteng. A quick reminder: If this PR can get a test suite, we are happy to merge :)

**Comment by omBratteng** [comment]
@Acconut Go is outside my knowledge, so I hope @Benehiko can write a test suite.

I have also used to same script as @perbu, and use 4MiB chunk size, as it uploads as AppendBlocks which are limited to 4MiB chunks because of the library version. I haven't tried with files over 195GB, as @Benehiko said, BlockBlobs are used for files over 195GB, then you'll get larger chunks.

Perhaps if one specified a higher chunk size than AppendBlob supports, then it would use BlockBlobs? @Benehiko

**Comment by Acconut** [comment]
Thanks for the insights about chunk sizes! Very helpful!

**Comment by omBratteng** [comment]
After some more testing, trying to get it to upload as a BlockBlob, I created a 225GiB null file.
I get this error
```
[tusd] 2021/01/25 22:40:18 event="ResponseOutgoing" status="500" method="HEAD" path="11c43c0a9c210ab84a123ee8444b7018" error="-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/ombratteng/.go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.9.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====
Description=The specified blob does not exist.
RequestId:c50faa0c-301e-0011-0f62-f3effd000000
Time:2021-01-25T21:40:18.7395143Z, Details:
   Code: BlobNotFound
   GET https://<account-name>.blob.core.windows.net/tusd-storage/11c43c0a9c210ab84a123ee8444b7018?blocklisttype=all&comp=blocklist&timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.9 (go1.15.7; darwin)]
   X-Ms-Client-Request-Id: [52eb16ab-30d7-4db9-7599-b86e1df76e02]
   X-Ms-Date: [Mon, 25 Jan 2021 21:40:18 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified blob does not exist.
   Content-Length: [215]
   Content-Type: [application/xml]
   Date: [Mon, 25 Jan 2021 21:40:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [BlobNotFound]
   X-Ms-Request-Id: [c50faa0c-301e-0011-0f62-f3effd000000]
   X-Ms-Version: [2018-11-09]


" requestId=""
```

But it generates and uploads the info file as a AppendBlob
```json
{
    "ID": "a3badcb0c96b0ebf7ceb9f5025dcde10",
    "Size": 241591910400,
    "SizeIsDeferred": false,
    "Offset": 0,
    "MetaData": {},
    "IsPartial": false,
    "IsFinal": false,
    "PartialUploads": null,
    "Storage": {
        "Container": "tusd-storage",
        "Key": "a3badcb0c96b0ebf7ceb9f5025dcde10",
        "Type": "azurestore"
    }
}
```

**Comment by Acconut** [comment]
Let's hope someone with Azure Storage experience can help us with this at some point!

**Comment by omBratteng** [comment]
@Acconut I have started looking into this, learning Go as i go. Forked it under https://github.com/arkivverket/tusd as we are dependent of this, we've assigned resources to fix this

**Comment by Benehiko** [comment]
> @Acconut Go is outside my knowledge, so I hope @Benehiko can write a test suite.
> 
> I have also used to same script as @perbu, and use 4MiB chunk size, as it uploads as AppendBlocks which are limited to 4MiB chunks because of the library version. I haven't tried with files over 195GB, as @Benehiko said, BlockBlobs are used for files over 195GB, then you'll get larger chunks.
> 
> Perhaps if one specified a higher chunk size than AppendBlob supports, then it would use BlockBlobs? @Benehiko

One can do that inside the azurestore -> NewUpload function. 

currently it's supposed to be switching between append -> block blob when file size exceeds append. Extract of the code below:

```go

       // Check if file size is greater than append blob max size
	if info.Size > store.Service.MaxAppendBlobSize {
		// Check if file size is greater than block blob max size
		if info.Size > store.Service.MaxBlockBlobSize {
			return nil, fmt.Errorf("azurestore: max upload of %v bytes exceeded MaxBlockBlobSize of %v bytes",
				info.Size, store.Service.MaxBlockBlobSize)
		} else {
			bb := store.Service.ContainerURL.NewBlockBlobURL(id)
			fileBlob = &FileBlob{
				BlockBlob: &bb,
			}
		}
	} else {
		ab := store.Service.ContainerURL.NewAppendBlobURL(id)
		fileBlob = &FileBlob{
			AppendBlob: &ab,
		}
		err := fileBlob.Create(ctx)
		if err != nil {
			return nil, err
		}
	}
```

**Comment by Benehiko** [comment]
> After some more testing, trying to get it to upload as a BlockBlob, I created a 225GiB null file.
> I get this error
> 
> ```
> [tusd] 2021/01/25 22:40:18 event="ResponseOutgoing" status="500" method="HEAD" path="11c43c0a9c210ab84a123ee8444b7018" error="-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/ombratteng/.go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.9.0/azblob/zc_storage_error.go:42
> ===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====
> Description=The specified blob does not exist.
> RequestId:c50faa0c-301e-0011-0f62-f3effd000000
> Time:2021-01-25T21:40:18.7395143Z, Details:
>    Code: BlobNotFound
>    GET https://<account-name>.blob.core.windows.net/tusd-storage/11c43c0a9c210ab84a123ee8444b7018?blocklisttype=all&comp=blocklist&timeout=61
>    Authorization: REDACTED
>    User-Agent: [Azure-Storage/0.9 (go1.15.7; darwin)]
>    X-Ms-Client-Request-Id: [52eb16ab-30d7-4db9-7599-b86e1df76e02]
>    X-Ms-Date: [Mon, 25 Jan 2021 21:40:18 GMT]
>    X-Ms-Version: [2018-11-09]
>    --------------------------------------------------------------------------------
>    RESPONSE Status: 404 The specified blob does not exist.
>    Content-Length: [215]
>    Content-Type: [application/xml]
>    Date: [Mon, 25 Jan 2021 21:40:17 GMT]
>    Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
>    X-Ms-Error-Code: [BlobNotFound]
>    X-Ms-Request-Id: [c50faa0c-301e-0011-0f62-f3effd000000]
>    X-Ms-Version: [2018-11-09]
> 
> 
> " requestId=""
> ```
> 
> But it generates and uploads the info file as a AppendBlob
> 
> ```json
> {
>     "ID": "a3badcb0c96b0ebf7ceb9f5025dcde10",
>     "Size": 241591910400,
>     "SizeIsDeferred": false,
>     "Offset": 0,
>     "MetaData": {},
>     "IsPartial": false,
>     "IsFinal": false,
>     "PartialUploads": null,
>     "Storage": {
>         "Container": "tusd-storage",
>         "Key": "a3badcb0c96b0ebf7ceb9f5025dcde10",
>         "Type": "azurestore"
>     }
> }
> ```

@omBratteng maybe the block blob isn't committed somehow, so it gets allocated, but not created... then it probably throws the error from 

    func (store AzureStore) GetUpload(ctx context.Context, id string) (handle handler.Upload, err error) { }

Does it indicate from where inside the tusd program is throwing the error?

**Comment by Benehiko** [comment]
Latest commit adds support on BlockBlob and AppendBlob (uses append by default). Also refactored the whole store to make it more readable and extendable. This latest commit also fixes the chunking issue mentioned by @perbu. The server adjusts the chunk size being sent to the azure store when something greater than the blob type's max chunk size is being used.

Note: _BlockBlob won't show up inside your container until the upload is fully completed due to it being only "comitted" after all chunks have been written_

@Acconut I have written the tests (which is passing on my local machine) but fails on GitHub - please advise.

**Comment by Acconut** [comment]
Thank you for the update, @Benehiko, and apologies for my late reply!

Shortly before your new commits, @omBratteng opened a second PR for an Azure implementation at https://github.com/tus/tusd/pull/458. It's unfortunate that there was redundant work but I am very grateful that there is an eager interest in this topic. Since I am no Azure expert, I wondered if you two, @Benehiko and @omBratteng, could have a look at both PR and see what the differences are. Based on this we could then decide as a community to focus our attention on one PR and avoid duplicate work. How does this sound to you? :)

> I have written the tests (which is passing on my local machine) but fails on GitHub - please advise.

@omBratteng has written in their PR that the tests on Github pass after upgrading the Go versions on the CI from 1.12 and 1.13 to 1.14 and 1.15. Maybe you can try that?

**Comment by Benehiko** [comment]
@Acconut I will check this out later today

**Comment by Benehiko** [comment]
@Acconut I reviewed some of @omBratteng's code which looks oddly very familiar to my code before I did a complete refactor on this commit https://github.com/Benehiko/tusd/commit/df249230ad0d79b1952b8b52658a82006cc7730c. Please see my review of his code here https://github.com/tus/tusd/pull/458#pullrequestreview-610366328

Anyhow, I refactored it due to bad structure, readability and some lacking features which were addressed in this thread e.g. "cannot upload chunk size greater than 4MiB". 

My code implements a good structure for easy further development with a good structure using the [uber style guide](https://github.com/uber-go/guide/blob/master/style.md). The code provides a solution for chunking files of any chunk size to the correct size of the supported blob type e.g. Append blob can only be 4MiB in chunk sizes, which means a tusd chunk size of 10MiB would be chunked further on the server side. The current implementation also provides a way for the tusd client to pass a mime type in the metadata tags on key "contentType" to specify the file content type and what it should be saved as on the azure blob store.

I can introduce further features and changes such as:
- changing the blob type on per upload
- changing the blob access type on per upload
- global flag indicating the blob type (override to the sizing mechanism with constraints) e.g. block blob uploads are the default instead of append.
- global flag indicating the blob access type (hot, cold etc)
- global flag indicating the container public access level e.g. none, on blobs only, on container. 

This can be done by the weekend. I already have it in the pipeline anyway ;)

**I am biased to my own PR, since I don't like seeing my own (bad) code ripped into a new PR like that with minimal changes under the banner of improvement. I know the previous code is bad that's why I refactored it ;D**

I honestly just wanted to contribute to this project due to having a good experience with implementing and using tusd - it's still running in one of my production environments (: 
I just hope that whichever one you guys and the community chose that it is the right one that would benefit this project. I know my code isn't the best and there are probably a 100 more features that could be implemented and improved upon, however, it does what it states - uploads a file to azure blob storage.

**Comment by gldraphael** [comment]
Hello @Acconut, if we're finding it hard to make a decision between this PR and https://github.com/tus/tusd/pull/458, may I suggest a community vote?
Would be nice if one of these could be merged.

Probably worth noting that @omBratteng has not (yet) responded to @Benehiko's [comment](https://github.com/tus/tusd/pull/458#pullrequestreview-610366328) in #458.

**Comment by lukasz-xfaang** [comment]
@Acconut @gldraphael 
Hi guys, we are really interested in seeing tus support Azure Blob Storage.
What is missing here?  As for whether this or PR 458 should be considered, I believe the earlier one should be considered first, especially if they are essentially implemented in a similar way.

**Comment by omBratteng** [comment]
Both PRs are similar, after months of no progress of getting tests added to this PR, I created my own branch based off of Benehiko's code, but used tusd main branch to get latest commits. I removed the append blob implementation, as I don't see any benefit of it because it is optimised for log files and similar, it also retains you to 4 MiB chunk size and 195 GiB max file size.
By only implementing Block blob, a future implementation of concurrent uploads is easier to implement, and reduces code complexity.
In addition I added the missing tests that was required by @Acconut.

A few other nice-haves that I implemented was the possibility to change blob/ container tier type, as one might be interested in having different tiers uploaded.

Plus support for using Azurite or non-standard Azure Blob Storage url, hopefully if Connection String gets implemented in the azure blob storage sdk (https://github.com/Azure/azure-storage-blob-go/issues/244), that would be the preferred method of connecting, as the connection string is much better solution of initialising a connection to a blob storage endpoint.

Support for Azurite is great if you need want to test functionality without using Azure, e.g. integration tests in Github workflows where you can spin up Azurite as a service container.

**Comment by Acconut** [comment]
@Benehiko Seeing that you closed this PR now, I just wanted to thank you very much for your contributions in the past! I am sorry that your PR didn't make it into tusd.

**Pull request closed without merging**
