### PR TITLE
Post receive disable

### PR DESCRIPTION
**Pull request by brandonkal**
This PR adds the option to disable to the post-receive hook via a new command line flag. It remains enabled by default.

Related: #239

### CODE REVIEW

**Comment by brandonkal** [comment]
Note that most of the doc changes are the result of Prettier cleaning things up. If this is an issue, feel free to edit this PR or let me know. I have made the doc changes its own commit to make review easier.

**Comment by Acconut** [comment]
Thank you very much for this PR!

It would be nice if you could undo the unrelated documentation changes as they make reviewing your patch a bit harder. Anyways, I think if we go ahead and offer a solution to disable the post-receive hook, we can also go a step further and allow users to disable/enable any event to they want. However, I am unsure whether this should be a blacklist (similar to your PR) or a whitelist where the user must explicitly activate each event.

The usage could look like this:
```sh
tusd -dir ./data -hooks-dir ./hooks -disable-hook-events post-receive,pre-create

# or with a whitelist

tusd -dir ./data -hooks-dir ./hooks -enable-hook-events post-create,post-finish
```

What do you think about this?

**Comment by Acconut** [comment]
> I would prefer the blacklist approach if it went that route as my docker-compose's command option is already quite long.

I can understand your reasoning but a whitelist is probably better in terms of future compatibility. If we are going to add another hook in the future, people to not have to opt out of it when they upgrade their tusd version.

> This is my first time hacking with golang so I am not sure how to go about parsing a string list like that.

I am happy to assist if you want to give it a try. The `strings` package (https://golang.org/pkg/strings/) should include all necessary tools. You basically just have to split the parameter at the comma character and eventually trim all additional whitespace.

**Comment by Acconut** [comment]
A whitelist for hooks has been added in https://github.com/tus/tusd/commit/f1fe5e26034504f084c97cd53cccc65271425095.

**Pull request closed without merging**
