### PR TITLE
Add test for content length on 404

### PR DESCRIPTION
**Pull request by gingermusketeer**
This is a test for an issue which was resolved in #31. This test was extracted from #29

### CODE REVIEW

**Comment by Acconut** [comment]
Thank you for this change. However, I implement it using a simpler approach in 88aed988f9646eb22caa15800e8d804f6d7c35f5. :)

**Comment by gingermusketeer** [comment]
Awesome. That is a lot simpler :)

**Comment by gingermusketeer** [comment]
@Acconut Looking at https://github.com/tus/tusd/blob/master/handler_test.go#L77 i am not sure if the test in 88aed988f9646eb22caa15800e8d804f6d7c35f5 is actually checking that the body length is 0. Thoughts?

**Comment by Acconut** [comment]
Oh man, right, I forgot. Thanks for this notice. I will fix this :)

**Comment by Acconut** [comment]
Addressed this in dd6ce926510984d0d05c6ee6b9786540d3a9c0c7.

**Pull request closed without merging**
