### PR TITLE
Upgrade Frey to v0.3.27 /cc @tersmitten

### PR DESCRIPTION
**Pull request by kvz**

### CODE REVIEW

**Comment by tersmitten** [comment]
Can you grant me push permissions so I can update this pull request?

**Comment by Acconut** [comment]
@tersmitten I just invited you to be a collaborator on this repository. Hope this helps

**Comment by tersmitten** [comment]
I'll try to push my changes tonight so this (and the other related pull requests) can be merged

**Comment by tersmitten** [comment]
I'm done

**Comment by kvz** [comment]
See https://github.com/transloadit/uppy-server/pull/11#issuecomment-271818826

**Pull request merged**
