### PR TITLE
Update Uid() func to v4 Unique id.

### PR DESCRIPTION
**Pull request by bienkma**
Reduce Collisions and Standard RFC 4122

### CODE REVIEW

**Comment by Acconut** [comment]
Do you mind explaining your thoughts behind this change?

**Comment by bienkma** [comment]
The uuidv4 description https://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates section uuidv4. "Some pseudorandom number generators lack necessary entropy to produce sufficiently pseudorandom numbers. For example, the WinAPI GUID generator, which uses a pseudorandom number generator, has been shown to produce UUIDs which follow a predictable pattern.[citation needed] RFC 4122 advises that "distributed applications generating UUIDs at a variety of hosts must be willing to rely on the random number source at all hosts. If this is not feasible, the namespace variant should be used."

**Comment by Acconut** [comment]
Thank you for this citation but I don't think this is necessary in our case. The Uid function uses the crypto/rand package which implements "a cryptographically secure pseudorandom number generator" (https://golang.org/pkg/crypto/rand/) for generating those UIDs. Therefore, I do not believe that it lacks the "necessary entropy to produce sufficiently pseudorandom numbers". What do you think?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Pull request closed without merging**
