### PR TITLE
feat: Enable returning relative URL to the client

### PR DESCRIPTION
**Pull request by endeverchen**
1. Add a parameter to indicate whether returning relative URL to the client.

### CODE REVIEW

**Comment by endeverchen** [comment]
related issue: #332

**Comment by Acconut** [comment]
Thank you for this PR! Before reviewing this properly, I do believe there is an edge case to cover: If one sends a POST request to `http://localhost/files` (no trailing slash) and the server returns `Location: vreuwghiewrhguirewh`, that would result in the upload URL being `http://localhost/vreuwghiewrhguirewh` which is not correct.

**Comment by endeverchen** [comment]
Thank you for pointing out the problem. I had fixed it in the latest push: If the request URI does not end with trailing slash, the base path will be added as prefix to it.

**Comment by innovate-invent** [comment]
Would you be interested in refactoring this to just swap out the callbacks at init for #341

**Comment by Acconut** [comment]
Good point @innovate-invent. With #341 we might not need this explicit feature anymore as users can configure the relative URL on their own.

**Pull request closed without merging**
