### PR TITLE
Adds Request headers to HTTP hooks and also adds the missing dependencies

### PR DESCRIPTION
**Pull request by miladz68**
This PR solves both issues #187 and #185 . 
I know that it a bad practice to address 2 seperate issues in a single PR, but I am new to making PRs and didn't plan it ahead.

on issue #185 in which I asked to pass all http request headers to http hooks: 
I tried to solve this by adding a HTTPRequestHeader field to FileInfo struct, then capture headers in the request and pass them when hooks are activated. I also had to modiy tests a little to make sure this work correctly.

on issue #187 I simply added the dependencies to the vendor directory.

again I am new to golang and PRs, so feel free to ask for modificaitons( or spliting this PR to 2 seperate PRs if necessary).
Thanks

### CODE REVIEW

**Comment by Acconut** [comment]
First of all, I want to thank you very much for spending your time working on this feature. While I agree that we should implement it, I see a few fundamental flaws in your approach (ignoring the dependency changes):

1. The HTTP headers are added to the FileInfo struct which has semantically nothing to do with the HTTP requests and  I don't see this as a good internal design. On the other hand, I am not sure where else to store this information, so I need to invest more time into this.
2. All HTTP headers from the request to tusd are directly added to the hook request and can overwrite important values which are needed for correct functionality and integrity (e.g. Content-Length, Content-Type, Host)
3. The hook handler is not able to distinguish between which headers have been set by tusd (e.g. Hook-Name) and which have been set by the client (e.g. Authorization). This may be a critical security vulnerability.

My solution would be to not add the client headers to the hook request headers but instead pass them inside the HTTP request body. In this way, there is no confusion about the origin of a single header pair. What do you think?

**Comment by miladz68** [comment]
I will create another PR, I know this is a mess

**Comment by miladz68** [comment]
@Acconut 
firstly forgive my broken English.
The solution that you are proposing is definitely better than mine.
but about the flaw number 1 that you have mentioned, I did not want to use FileInfo at first, but when I passed the the headers as another struct I faced a problem here[(https://github.com/tus/tusd/blob/master/cmd/tusd/cli/hooks.go#L33)]. Basically adding another struct to this line makes hookDataStore not an instance of datastore, and I couldn't find a way to get around this (although I didn't spend much time thinking). 
I will try to look deeper into the code and fix the flaws that you are mentioning

**Comment by Acconut** [comment]
> Basically adding another struct to this line makes hookDataStore not an instance of datastore, and I couldn't find a way to get around this (although I didn't spend much time thinking).

I am not sure what you mean, you should be able to add another property to the hookDataStore struct without violating interfaces. But I don't think it matters anymore. :)

> I will try to look deeper into the code and fix the flaws that you are mentioning

:+1: Feel free to ask if you have more questions

**Pull request closed without merging**
